version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  nginx:
    image: nginx
    restart: always
    ports:
      - "8080:80"
      - "80:80"
      - "443:443"
    links:
      - backend
    volumes:
      - ./data/nginx:/etc/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  backend:
    image: ghcr.io/fossinating/tarheel-compass-server:staging
    restart: always
    env_file:
      - path: .env
        required: true
    links:
      - db
  data:
    image: ghcr.io/fossinating/tarheel-compass-data:staging
    restart: on-failure:3
    env_file:
      - path: .env
        required: true
    links:
      - db
  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"